[project]
name = "lanscape"
version = "0.0.0"
authors = [
  { name="Michael Dennis", email="michael@dipduo.com" },
]
description = "A python based local network scanner"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["network", "scanner", "lan", "local", "python"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "Flask>=3.0,<5.0",
    "psutil>=6.0,<7.0",
    "requests>=2.32,<3.0", 
    "setuptools",
    "scapy>=2.3.2,<3.0",
    "tabulate==0.9.0",
    "pydantic",
    "icmplib"
]
[project.urls]
Homepage = "https://github.com/mdennis281/py-lanscape"
Issues = "https://github.com/mdennis281/py-lanscape/issues"

[project.scripts]
lanscape = "lanscape.ui.main:main"

[tool.setuptools]
packages = { find = { include = ["lanscape*"], exclude = ["support*", "tests*"] } }

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
