name: Package and Publish

on:
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip running tests'
        required: false
        default: 'false'
      skip_upload:
        description: 'Skip uploading to PyPI'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Match your local version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
          python -m pip install pytest
          python -m pip install -r requirements.txt

      - name: Run tests
        if: ${{ github.event.inputs.skip_tests != 'true' }}
        run: |
          python -m unittest
          
      - name: Clean dist directory
        run: |
          rm -rf dist
          rm -rf ./**/*.egg-info

      - name: Build package
        run: |
          python -m build

      - name: Check package
        if: ${{ github.event.inputs.skip_upload != 'true' }}
        run: |
          python -m twine check dist/*

      - name: Upload to PyPI
        if: ${{ github.event.inputs.skip_upload != 'true' }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload --repository pypi dist/*
