name: PyPi Package and Publish

on:
  push:
    tags:
      - 'releases/*'
      - 'pre-releases/*'

jobs:
  publish:
    uses: ./.github/workflows/pypi-publish.yml
    with:
      branch: ${{ github.ref_name }}
      version: ${{ replace(replace(github.ref_name, 'releases/', ''), 'pre-releases/', '') }}
    secrets: inherit
