name: Release Trigger - Tag Push

on:
  push:
    tags:
      - 'releases/*'
      - 'pre-releases/*'

jobs:
  publish:
    uses: ./.github/workflows/pypi-publish.yml
    with:
      branch: ${{ github.ref }}
      version: ${{ github.ref_name }}
    secrets: inherit
