name: Reusable PyPI Publish

on:
  workflow_call:
    inputs:
      branch:
        description: "Branch or tag to checkout before publishing"
        required: true
        type: string
      version:
        description: "Version number to apply to the package"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
          python -m pip install -r requirements.txt

      - name: Clean dist directory
        run: |
          rm -rf dist
          rm -rf ./**/*.egg-info

      - name: Update version in pyproject.toml
        run: |
          VERSION='${{ inputs.version }}'
          sed -i "s/^version = \".*\"/version = \"${VERSION}\"/" pyproject.toml

      - name: Build package
        run: |
          python -m build

      - name: Check package
        run: |
          python -m twine check dist/*

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          TWINE_REPOSITORY: pypi
        run: |
          python -m twine upload --repository pypi dist/*
