name: Tag New Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      tag_name: ${{ steps.create_tag.outputs.tag_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from commit message
        id: extract_version
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B | head -n1)
          VERSION_PART=$(echo "$COMMIT_MSG" | cut -d' ' -f1)
          if echo "$VERSION_PART" | grep -q '^[0-9]\+\.[0-9]\+\.[0-9]\+$'; then
            echo "version=$VERSION_PART" >> "$GITHUB_OUTPUT"
          else
            echo "Commit message does not start with a semantic version. Skipping tag creation."
          fi

      - name: Create tag
        if: ${{ steps.extract_version.outputs.version != '' }}
        id: create_tag
        run: |
          VERSION="${{ steps.extract_version.outputs.version }}"
          TAG_NAME="releases/${VERSION}"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
          echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"

  publish:
    needs: tag
    if: ${{ needs.tag.outputs.version != '' }}
    uses: ./.github/workflows/pypi-publish.yml
    with:
      branch: ${{ github.ref_name }}
      version: ${{ needs.tag.outputs.version }}
    secrets: inherit
